-- Bảng Khách hàng
CREATE TABLE CUSTOMERS (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR2(20) UNIQUE NOT NULL, -- Ví dụ: KH0001
    full_name NVARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(15) UNIQUE NOT NULL,
    email VARCHAR2(100),
    birthday DATE,
    address NVARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng Nhân viên
CREATE TABLE STAFFS (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_code VARCHAR2(20) UNIQUE NOT NULL, -- Ví dụ: NV001
    full_name NVARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(15),
    role VARCHAR2(50), -- Stylist, Cashier, Manager
    base_salary NUMBER(15, 2) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1, -- 1: Đang làm việc, 0: Đã nghỉ
    created_at DATE DEFAULT SYSDATE
);

-- Bảng Chấm công & Ca làm việc
CREATE TABLE WORK_SHIFTS (
    shift_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id NUMBER REFERENCES STAFFS(staff_id),
    check_in TIMESTAMP,
    check_out TIMESTAMP,
    shift_date DATE DEFAULT TRUNC(SYSDATE),
    note NVARCHAR2(255)
);

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

-- Bảng Danh mục (Để phân loại Cắt, Uốn, Nhuộm hoặc Mỹ phẩm bán lẻ)
CREATE TABLE CATEGORIES (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name NVARCHAR2(100) NOT NULL,
    category_type VARCHAR2(20) CHECK (category_type IN ('SERVICE', 'PRODUCT'))
);

-- Bảng Dịch vụ (Menu của Salon)
CREATE TABLE SERVICES (
    service_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id NUMBER REFERENCES CATEGORIES(category_id),
    service_name NVARCHAR2(200) NOT NULL,
    base_price NUMBER(15, 2) NOT NULL, -- Giá gốc
    duration_minutes NUMBER, -- Thời gian thực hiện ước tính
    description NVARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1
);

-- Bảng Sản phẩm (Mỹ phẩm, thuốc nhuộm, dầu gội...)
CREATE TABLE PRODUCTS (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id NUMBER REFERENCES CATEGORIES(category_id),
    product_name NVARCHAR2(200) NOT NULL,
    unit NVARCHAR2(50), -- Chai, Tuýp, Bộ
    selling_price NUMBER(15, 2), -- Giá bán lẻ cho khách
    stock_quantity NUMBER DEFAULT 0, -- Tồn kho hiện tại
    min_stock_level NUMBER DEFAULT 5, -- Mức tối thiểu để hệ thống cảnh báo
    is_active NUMBER(1) DEFAULT 1
);

-- Bảng Voucher & Khuyến mãi
CREATE TABLE VOUCHERS (
    voucher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_code VARCHAR2(50) UNIQUE NOT NULL,
    discount_value NUMBER(15, 2), -- Số tiền giảm hoặc %
    discount_type VARCHAR2(10) CHECK (discount_type IN ('AMOUNT', 'PERCENT')),
    start_date DATE,
    end_date DATE,
    min_order_value NUMBER(15, 2) DEFAULT 0
);

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

-- Bảng Lịch hẹn
CREATE TABLE APPOINTMENTS (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES CUSTOMERS(customer_id),
    staff_id NUMBER REFERENCES STAFFS(staff_id), -- Thợ yêu cầu
    appointment_time TIMESTAMP NOT NULL,
    status NVARCHAR2(50) CHECK (status IN (N'Chờ xác nhận', N'Đã xác nhận', N'Đã đến', N'Đã hủy')),
    note NVARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng Hóa đơn (Chính)
CREATE TABLE INVOICES (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_code VARCHAR2(30) UNIQUE NOT NULL, -- Ví dụ: HD20231027001
    customer_id NUMBER REFERENCES CUSTOMERS(customer_id),
    cashier_id NUMBER REFERENCES STAFFS(staff_id), -- Người thu ngân
    total_raw_amount NUMBER(15, 2), -- Tổng tiền trước giảm giá
    discount_amount NUMBER(15, 2) DEFAULT 0,
    final_amount NUMBER(15, 2), -- Số tiền thực thu
    payment_method NVARCHAR2(50), -- Tiền mặt, Chuyển khoản, Ví điện tử, Quẹt thẻ
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng Chi tiết hóa đơn (Dịch vụ & Sản phẩm đã dùng)
CREATE TABLE INVOICE_DETAILS (
    detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id NUMBER REFERENCES INVOICES(invoice_id),
    item_id NUMBER, -- ID của Service hoặc Product
    item_type VARCHAR2(20) CHECK (item_type IN ('SERVICE', 'PRODUCT')),
    quantity NUMBER DEFAULT 1,
    unit_price NUMBER(15, 2),
    staff_id NUMBER REFERENCES STAFFS(staff_id), -- Thợ thực hiện trực tiếp để tính hoa hồng
    commission_value NUMBER(15, 2) DEFAULT 0 -- Số tiền hoa hồng thợ nhận được từ mục này
);

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

-- Nhà cung cấp
CREATE TABLE SUPPLIERS (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name NVARCHAR2(200) NOT NULL,
    phone VARCHAR2(15),
    address NVARCHAR2(255)
);

-- Phiếu nhập kho
CREATE TABLE INVENTORY_RECEIPTS (
    receipt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id NUMBER REFERENCES SUPPLIERS(supplier_id),
    import_date DATE DEFAULT SYSDATE,
    total_value NUMBER(15, 2),
    note NVARCHAR2(500)
);

-- Chi tiết nhập kho
CREATE TABLE INVENTORY_DETAILS (
    inv_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id NUMBER REFERENCES INVENTORY_RECEIPTS(receipt_id),
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    quantity NUMBER NOT NULL,
    import_price NUMBER(15, 2),
    expiry_date DATE -- Hạn sử dụng (quan trọng cho hóa chất nhuộm/uốn)
);

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

-- Sổ Quỹ Thu - Chi (Dùng cho báo cáo thuế hộ kinh doanh)
CREATE TABLE CASHBOOK (
    entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    entry_type VARCHAR2(10) CHECK (entry_type IN ('THU', 'CHI')),
    category NVARCHAR2(100), -- Doanh thu bán lẻ, Chi lương, Chi tiền điện, Chi nhập hàng...
    amount NUMBER(15, 2) NOT NULL,
    payment_method NVARCHAR2(50),
    reference_id NUMBER, -- ID của Invoice hoặc Inventory_Receipt nếu có
    note NVARCHAR2(500)
);
